In [1]:
import numpy as np

In [5]:
def rotation_from_euler(a, b, g):
    Rx=np.array([[1, 0, 0], [0, np.cos(a), -np.sin(a)], [0, np.sin(a), np.cos(a)]], dtype=float)
    Ry=np.array([[np.cos(b), 0, np.sin(b)], [0, 1, 0], [-np.sin(b), 0, np.cos(b)]], dtype=float)
    Rz=np.array([[np.cos(g), -np.sin(g), 0], [np.sin(g), np.cos(g), 0], [0, 0, 1]], dtype=float)
    return np.dot(Rz, np.dot(Ry, Rx))
    
def get_angle_axis(R):
    theta=np.arccos((np.trace(R)-1)/2.0)
    n=(1.0/2.0*np.sin(theta))*np.array([R[2, 1] - R[1, 2], R[0, 2] - R[2, 0], R[1, 0] - R[0, 1]])
    return theta, n

In [8]:
R_i=rotation_from_euler(0, 0, 0)
R_d=rotation_from_euler(np.pi/2, 0, 0)

R_id=np.dot(np.transpose(R_i), R_d)

theta, n = get_angle_axis(R_id)
print np.round(R_id)
print np.round(theta, 2)
print n


[[ 1.  0.  0.]
 [ 0.  0. -1.]
 [ 0.  1.  0.]]
1.57
[1. 0. 0.]
